stages:
  train_model:
    cmd: python src/train.py
    deps:
    - data/train.csv
    - src/train.py
    outs:
    - models/RandomForest.joblib
  train_lr:
    cmd: python src/train.py model=lr
    deps:
    - data/train.csv
    - src/train.py
    outs:
    - models/LogisticRegression.joblib
